version: "3.9"

services:
  backend:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Esto monta tu código fuente en el contenedor (útil en desarrollo)
    env_file:
      - .env  # Variables de entorno
    depends_on:
      - redis
    command: >
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  redis:
    image: redis:7.2-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
